[package]
name = "xander1998/staxframework"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
react-roblox = "jsdotlua/react-roblox@17.1.0"
promise = "joshuaclarkelua/promise@4.0.12"