--[[
    SERVICES
--]]
-- local _ReplicatedStorage = game:GetService("ReplicatedStorage")
-- local ServerScriptService = game:GetService("ServerScriptService")
-- local ServerStorage = game:GetService("ServerStorage")

--[[
    IMPORTS
--]]
-- local Types = require(_ReplicatedStorage.framework.stax.types.core)

-- local PlayerService: Types.Service = {
-- 	name = "PlayerService",
-- 	Players = {},
-- }

-- function PlayerService.Load(next: () -> nil)
-- 	next()
-- end

-- function PlayerService.Initialize(next: () -> nil)
-- 	next()
-- end

-- function PlayerService.Start(next: () -> nil)
-- 	next()
-- end

-- function PlayerService.Stop(next: () -> nil)
-- 	next()
-- end
